/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FormBuilder {
        "schema": any;
    }
}
declare global {
    interface HTMLFormBuilderElement extends Components.FormBuilder, HTMLStencilElement {
    }
    var HTMLFormBuilderElement: {
        prototype: HTMLFormBuilderElement;
        new (): HTMLFormBuilderElement;
    };
    interface HTMLElementTagNameMap {
        "form-builder": HTMLFormBuilderElement;
    }
}
declare namespace LocalJSX {
    interface FormBuilder {
        "schema"?: any;
    }
    interface IntrinsicElements {
        "form-builder": FormBuilder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "form-builder": LocalJSX.FormBuilder & JSXBase.HTMLAttributes<HTMLFormBuilderElement>;
        }
    }
}
